name: Noetic

on:
  push:

    branches: [ master ]
    paths-ignore:
      - '**/README.md'

  pull_request:
    branches: [ master ]

  # schedule:
  #   - cron:  '0 0 * * *' # at the end of every day

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  # amd64_build:
  #   runs-on: ubuntu-20.04

  #   env:
  #     PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}

  #   steps:

  #     - uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0

  #     - name: Checkout CI scripts
  #       uses: actions/checkout@v3
  #       with:
  #         repository: ctu-mrs/ci_scripts
  #         path: .ci_scripts
  #         token: ${{ secrets.PUSH_TOKEN }}

  #     - name: Install ROS
  #       run: .ci_scripts/package_build/install_ros.sh

  #     - name: Build
  #       run: .ci_scripts/package_build/build_package.sh

  #     - name: Deploy
  #       run: .ci_scripts/package_build/deploy_deb.sh

  arm64_build:
    runs-on: ubuntu-20.04

    env:
      PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}

    steps:

      # - uses: actions/checkout@v3
      #   with:
      #     fetch-depth: 0

      # - name: Checkout CI scripts
      #   uses: actions/checkout@v3
      #   with:
      #     repository: ctu-mrs/ci_scripts
      #     path: .ci_scripts
      #     token: ${{ secrets.PUSH_TOKEN }}

      - name : Build system
        uses: uraimo/run-on-arch-action@v2.5.0
        with:
          arch: armv7
          distro: ubuntu20.04
          run: |
            uname -a
            echo ::set-output name=uname::$(uname -a)

           # .ci_scripts/package_build/install_ros.sh
           # .ci_scripts/package_build/build_package.sh
           # .ci_scripts/package_build/deploy_deb.sh

      # - name: Checkout CI scripts
      #   uses: actions/checkout@v3
      #   with:
      #     repository: ctu-mrs/ci_scripts
      #     path: .ci_scripts
      #     token: ${{ secrets.PUSH_TOKEN }}

      # - name: Install ROS
      #   run: 

      # - name: Build
      #   run: .ci_scripts/package_build/build_package.sh

      # - name: Deploy
      #   run: .ci_scripts/package_build/deploy_deb.sh
